// dom.js — Caché de nodos del DOM + constantes de clases de presentación.
// Un único `getElementById` por nodo al cargar; el resto del código usa `el`.

export const el = {
  card: document.getElementById("card"),
  headerBar: document.getElementById("header-bar"),
  pill: document.getElementById("pill"),
  pillGaugeArc: document.getElementById("pill-gauge-arc"),
  pillPct: document.getElementById("pill-pct"),
  pillBarFill: document.getElementById("pill-bar-fill"),
  full: document.getElementById("full"),
  planName: document.getElementById("plan-name"),
  sessionBlock: document.getElementById("session-block"),
  sessionPct: document.getElementById("session-pct"),
  sessionFill: document.getElementById("session-fill"),
  sessionSpark: document.getElementById("session-spark"),
  sessionSparkArea: document.getElementById("session-spark-area"),
  sessionSparkPoly: document.getElementById("session-spark-poly"),
  sessionReset: document.getElementById("session-reset"),
  weeklyBlock: document.getElementById("weekly-block"),
  weeklyPct: document.getElementById("weekly-pct"),
  weeklyFill: document.getElementById("weekly-fill"),
  weeklyReset: document.getElementById("weekly-reset"),
  contextLine: document.getElementById("context-line"),
  contextLabel: document.getElementById("context-label"),
  contextPct: document.getElementById("context-pct"),
  freshness: document.getElementById("freshness"),
  schemaWarn: document.getElementById("schema-warn"),
  refreshBtn: document.getElementById("refresh-btn"),
  pinBtn: document.getElementById("pin-btn"),
  hideBtn: document.getElementById("hide-btn"),
  settingsBtn: document.getElementById("settings-btn"),
  settingsClose: document.getElementById("settings-close"),
  metricsView: document.getElementById("metrics-view"),
  settingsView: document.getElementById("settings-view"),
  optTranslucent: document.getElementById("opt-translucent"),
  optOnTop: document.getElementById("opt-on-top"),
  optCollapsed: document.getElementById("opt-collapsed"),
  optPillStyle: document.getElementById("opt-pill-style"),
  optTheme: document.getElementById("opt-theme"),
  optAccent: document.getElementById("opt-accent"),
  optShowContext: document.getElementById("opt-show-context"),
  optRememberPos: document.getElementById("opt-remember-pos"),
  optAutostart: document.getElementById("opt-autostart"),
  optClose: document.getElementById("opt-close"),
  optStatusline: document.getElementById("opt-statusline"),
  optNotify: document.getElementById("opt-notify"),
  optNotifyThreshold: document.getElementById("opt-notify-threshold"),
  optBorderGlow: document.getElementById("opt-border-glow"),
  optTrayStatic: document.getElementById("opt-tray-static"),
  optBorderNormal: document.getElementById("opt-border-normal"),
  optBorderWarn: document.getElementById("opt-border-warn"),
  optBorderCrit: document.getElementById("opt-border-crit"),
  borderReset: document.getElementById("border-reset"),
  optLang: document.getElementById("opt-lang"),
  positionGrid: document.getElementById("position-grid"),
  resizeGrip: document.getElementById("resize-grip"),
  // Aviso de actualización
  updateBanner: document.getElementById("update-banner"),
  updateText: document.getElementById("update-text"),
  updateInstall: document.getElementById("update-install"),
  updateDismiss: document.getElementById("update-dismiss"),
  updateMute: document.getElementById("update-mute"),
  // Aviso de dependencias del sistema
  depsBanner: document.getElementById("deps-banner"),
  depsText: document.getElementById("deps-text"),
  depsToggle: document.getElementById("deps-toggle"),
  depsDismiss: document.getElementById("deps-dismiss"),
  depsDetail: document.getElementById("deps-detail"),
  depsList: document.getElementById("deps-list"),
  depsCmd: document.getElementById("deps-cmd"),
  depsCopy: document.getElementById("deps-copy"),
  // Ajustes de actualización
  updCurrent: document.getElementById("upd-current"),
  updCheck: document.getElementById("upd-check"),
  updStatus: document.getElementById("upd-status"),
};

export const SOURCE_CLASSES = ["source-hook", "source-logs", "source-sync", "source-none"];
export const SEVERITY_CLASSES = ["sev-warning", "sev-critical"];
